#!/bin/bash

colcon build --packages-select colcon build --packages-select \
     welt_launch welt_cam \
    sauvc_object_detection sauvc_launch sauvc_missions sauvc_movement sauvc_interfaces  \
    stingray_cam stingray_recorder stingray_devices stingray_object_detection stingray_interfaces stingray_launch stingray_missions stingray_movement stingray_utils \
    stingray_core_communication stingray_core_interfaces stingray_core_launch