FROM hydronautics/stingray:latest

# RUN apt update && apt install -y --no-install-recommends 

RUN echo 'source /additional_packages/install/setup.bash' >> /root/.bashrc

WORKDIR /welt_auv
CMD ["bash"]
