FROM hydronautics/stingray:latest

RUN apt update && apt install -y --no-install-recommends ros-iron-rmw-cyclonedds-cpp

RUN echo 'source /additional_packages/install/setup.bash' >> /root/.bashrc

WORKDIR /welt_auv
CMD ["bash"]
