FROM hydronautics/welt_auv:tx2

WORKDIR /welt_auv
COPY src src
COPY *.sh /welt_auv/
RUN /bin/bash -c "source /additional_packages/install/setup.bash && /welt_auv/build_vision.sh"

RUN echo 'source /welt_auv/install/setup.bash' >> /root/.bashrc

ENTRYPOINT [ "/welt_auv/run_vision.sh" ]

CMD ["bash"]
