services:
  welt_auv_control:
    image: ${WELT_AUV_CONTROL_IMAGE:-hydronautics/welt_auv:control}
    container_name: ${WELT_AUV_CONTROL_CONTAINER:-s_welt_auv_control}
    ipc: host
    network_mode: host
    command: ros2 launch welt_launch control.launch.py
    restart: unless-stopped
    volumes:
      - ${WELT_DATA_DIR:-${HOME}/welt}:/welt
    profiles:
      - core


  welt_auv_od:
    image: ${WELT_AUV_OD_IMAGE:-hydronautics/welt_auv:od}
    container_name: ${WELT_AUV_OD_CONTAINER:-s_welt_auv_od}
    ipc: host
    platform: ${WELT_AUV_OD_PLATFORM:-linux/arm64}
    runtime: ${DOCKER_NVIDIA_RUNTIME:-nvidia}
    gpus: ${DOCKER_GPUS:-all}
    command: ros2 launch welt_launch od.launch.py
    restart: unless-stopped
    volumes:
      - ${WELT_DATA_DIR:-${HOME}/welt}:/welt
    profiles:
      - core
      - vision

  rviz2:
    image: husarion/rviz2:humble-11.2.11-20240320
    container_name: s_rviz2
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    profiles:
      - debug
      - visualize

  recorder:
    image: ros:humble-ros-base
    container_name: s_recorder
    ipc: host
    volumes:
      - ${ROSBAG_DIR:-${HOME}/rosbags}:/rosbags
    command: >
      bash -lc "timeout ${RECORDER_TIMEOUT_SEC:-300} ros2 bag record -o /rosbags/rosbag_$$(date +%d-%m-%y__%H-%M) --compression-mode file --compression-format zstd -a"
    profiles:
      - debug
    restart: no
