services:
  welt_auv_control:
    image: hydronautics/welt_auv:control
    container_name: s_welt_auv_control
    ipc: host
    networks:
      - welt_net
    command: ros2 launch welt_launch control.launch.py
    restart: unless-stopped

  welt_auv_od:
    image: hydronautics/welt_auv:od
    container_name: s_welt_auv_od
    ipc: host
    networks:
      - welt_net
    platform: linux/arm64
    runtime: nvidia
    gpus: all
    command: ros2 launch welt_launch vision_yolov8.launch.py
    restart: unless-stopped

  zed_ros2:
      image: hydronautics/zed_ros2:l4t-r36.3.0-s4.2.5
      container_name: s_zed_ros2
      # image: hydronautics/zed_ros2:l4t-r36.3.0-s4.2.5-neural # for neural
      # container_name: s_zed_ros2_neural # for neural
      ipc: host
      networks:
        - welt_net
      runtime: nvidia
      gpus: all
      privileged: true
      volumes:
        - /dev:/dev
        - /dev/shm:/dev/shm
        - /usr/local/zed/resources:/usr/local/zed/resources
        - /usr/local/zed/settings:/usr/local/zed/settings
      command: ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zedm

  rviz2:
    image: husarion/rviz2:humble-11.2.11-20240320
    container_name: s_rviz2
    ipc: host
    networks:
      - welt_net
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    profiles:
      - debug
      - visualize

  recorder:
    image: ros:humble-ros-base
    container_name: s_recorder
    ipc: host
    networks:
      - welt_net
    volumes:
      - ${HOME}/rosbags:/rosbags
    command: ros2 bag record -o /rosbags/rosbag_$(date +%d-%m-%y__%H-%M") -a
    profiles:
      - debug

networks:
  welt_net:
    driver: host
